<br><br>
<center>
<h1 style="font-size: 24px;"><b> </b></h1>
    <h1 style="font-size: 24px;"><b>Data Afrique Hub Community </b></h1>
</center>
 <br><br>
<center>
    <hr style="height: 4px; background-color: blue;">
    <br>
    <br>
        <h1 style="font-size: 24px;"><b>Initiation à Python Pour la Data Science</b></h1>
        <h3 style="font-size: 24px;"><b>Traitement de Données avec Pandas</b></h3>
         <h3 style="font-size: 24px;"><b>Exercices</b></h3>



</center>
  <br><br>
   <hr style="height: 4px; background-color: blue;">
  <br><br>


<center>
     <br><br>
    <h3><strong>ANNÉE DE FORMATION: 2024</strong></h3>
</center>
<br><br>
<br><br>

### $$\text{Chargement  de Pandas sous le nom pd }$$

In [ ]:
#charger pandas sous le nom pd

### $$\text{Les séries }$$

In [ ]:
#Créez une série appelée temperature qui représente les températures quotidiennes d'une semaine (7 jours)
#d'une semaine (7 jours). Utilisez des valeurs de température au hasard, par exemple, entre 20 et 30.

In [ ]:
#Affichez la série temperature

In [ ]:
#Ajoutez des index pour représenter les jours de la semaine (Lundi', 'Mardi', ..., 'Dimanche').

In [ ]:
#Affichez à nouveau la série avec les nouveaux index

In [ ]:
#Accédez à la température du 'Mercredi'.

In [ ]:
#Calculez et afficher la moyenne des températures de la semaine.

In [ ]:
#Trouvez le jour avec la température maximale.

### $$\text{Nettoyage et préparation des données}$$

### $$\text{Chargement du fichier}$$

In [ ]:
url = "https://raw.githubusercontent.com/wesm/pydata-book/3rd-edition/datasets/titanic/train.csv"
#Chargement du fichier train.csv dans un dataframe de nom donner
donner =

### $$\text{Les dimensions du dataframe}$$

In [ ]:
#Les dimensions du dataframe

### $$\text{Les 5 première ligne du dataframe}$$

In [ ]:
#Afficher les 5 première ligne du dataframe

### $$\text{Les 5 dernière ligne du dataframe}$$

In [ ]:
#Les 5 dernière ligne du dataframe

### $$\text{Les information sur le dataframe}$$

In [ ]:
#Les information sur le dataframe

## Traitement 1

### $$\text{Effacer les lignes contenant les valeurs manquante le dataframe}$$

In [ ]:
#Effacer les lignes contenant les valeurs manquante le dataframe
 donne1 =

In [ ]:
#Les dimensions du donne1

In [ ]:
#Les information sur le donne1

## Traitement 2

### $$\text{liste des colonnes contenant  les valeurs manquantes}$$

In [ ]:
#liste des colonnes contenant  les valeurs manquantes
colonnes_vides =

In [ ]:
#Afficher la liste des colonnes vides

### $$\text{Effacer les colonnes Cabin et Embarked }$$

In [ ]:
#Effacer les colonnes Cabin et Embarked
data2 =

### $$\text{Remplacer les valeurs manquantes par 18}$$

In [ ]:
#Remplacer les valeurs manquantes par 18
data3 =

In [ ]:
#Les dimensions de data3